checks:
    php: true

filter:
    excluded_paths:
        - 'tests/'
        - 'vendor/'
        - 'styles/'
        - 'locales/'
        - 'doc/'
        - 'review/'

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

build:
    environment:
        php:
            version: 7.0
            ini:
                'date.timezone': 'Europe/Berlin'
    tests:
        override:
            -
                command: phpunit --coverage-clover=review/coverage
                coverage:
                    file: review/coverage
                    format: php-clover
